config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get     '/help',     to: 'static_pages#help'
  get     '/about',    to: 'static_pages#about'
  get     '/contact',  to: 'static_pages#contact'
  get     '/signup',   to: 'users#new'
  post    '/signup',   to: 'users#create'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# Retorna o digest de hash da string dada
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
	end

	# Retorna um token aleatório
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	# Retorna o digest de hash da string dada
	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

	# Retorna um token aleatório
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Lembra um usuário no banco de dados para uso em sessões persistentes.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	 # Retorna true se o token fornecido corresponder ao digest
	 def authenticated?(remember_token)
		 return false if remember_digest.nil?
		 BCrypt::Password.new(remember_digest).is_password?(remember_token)
	 end

	 # Esquecendo um usuário
	 def forget
	 	update_attribute(:remember_digest, nil)
	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  	render html: "Olá mundo Rails!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "email ou senha inválidos..."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about  	
  end

  def contact  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Bem vindo ao Bolão do brasileirão 2017..."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Atualização concluida com sucesso..."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuário deletado com sucesso."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Para ter acesso a está página o usuário deve estar logado."
        redirect_to login_url
      end
    end

    # Confirma se o usuário está correto
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Bolão do brasileirão 2017"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Registra o usuário especificado
  def log_in(user)
    session[:user_id] = user.id
  end

  # Lembra um usuário em uma sessão persistente
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Retorna o usuário correspondente ao cookie token de lembrança.
  def current_user
  if (user_id = session[:user_id])
    @current_user ||= User.find_by(id: user_id)
  elsif (user_id = cookies.signed[:user_id])
    user = User.find_by(id: user_id)
    if user && user.authenticated?(cookies[:remember_token])
      log_in user
      @current_user = user
    end
  end
end

  # Retorna true se o usuário estiver conectado, false caso contrário
  def logged_in?
    !current_user.nil?
  end

  # Desconecta o usuário atual
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Esquece uma sessão persistente
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Desconecta o usuário atual.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Bolão do brasileirão 2017 &copy; todos os direitos reservados design by Estevam
	</small>
	<nav>
		<ul>
			<li><%= link_to "Regras", about_path %></li>
			<li><%= link_to "Contatos", contact_path %></li>
			<li><a href="http://globoesporte.globo.com/" target="_blanck">Nóticias</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  	<div class="container">
  		<%= link_to "Bolão do brasileirão 2017", root_path, id: "logo" %>
  		<nav>
  			<ul class="nav navbar-nav navbar-right">
  				<li><%= link_to "Home", root_path %></li>
  				<li><%= link_to "Ajuda", help_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Usuários", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Conta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sair", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
  				<li><%= link_to "Login", login_path %></li>
          <% end %>
  			</ul>
  		</nav>
  	</div>
</header>

app/views/layouts/_shim.html.erb
<script type="text/javascript">
	  var jumboHeight = $('.jumbotron').outerHeight();
	    function parallax(){
	      var scrolled = $(window).scrollTop();
	 $('.bg').css('height', (jumboHeight-scrolled) + 'px');
	 }
	 $(window).scroll(function(e){
	  parallax();
	});
	</script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    	<%= yield %>
    </div>
    <div class="container-fluid">
      <%= debug(params) if Rails.env.development? %>
    	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    Este formulário contém <%= pluralize(@user.errors.count, "error") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "Regras") %>
<h1>Regras</h1>

	<p>
		Página de regras do site.
	</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contatos") %>
<h1>Contatos</h1>
<p>
	páginas para os usuários entrareem em contato com o nosso site.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Ajuda") %>
<h1>Ajuda</h1>
	<p>
		Está página é para tirar duvidas sobre o site.
	</p>

app/views/static_pages/home.html.erb
<div class="bg"><%= image_tag("bg.jpg", alt: "bg", class: "img-responsive") %></div>
<div class="center jumbotron">
	<h1>Bolão do brasileirão 2017</h1>
	<h2>
		Bem vindos! Ao Bolão do brasileirão 2017
	</h2>

	<%= link_to "Cria uma conta agora", signup_path, class: "btn btn-lg btn-success" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, "Nome" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "Senha" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmação" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Tem certeza que deseja deletar o usuário selecionado?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Editar perfil") %>
<% provide(:button_text, "Salvar alterações") %>
<h1>Editar perfil</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Alterar</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Usuários') %>
<h1>Todos os usuários</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Criar conta") %>
<% provide(:button_text, "Cria minha conta") %>
<h1>Cria conta</h1>
<div class="row">
  <div class="col-md-4  col-md-offset-4">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<di class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</di>